name: test

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.x

    - name: Install Redis
      run: |
        sudo apt-get update
        sudo apt-get install redis-server

    - name: Start Redis server
      run: redis-server &

    - name: Run tests
      run: go test -v ./...

    - name: Clean up Redis
      run: |
        redis-cli flushall
        sudo killall redis-server
